// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipbkhfghishtdlypfwap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwYmtoZmdoaXNodGRseXBmd2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTg4NzksImV4cCI6MjA2OTc3NDg3OX0.j5R_-6hdXs7UvCE9KaNj_BXs8miGYtG7vJM077akNhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});